name: Ruff Lint

on: [pull_request]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff
      run: ruff check .